# Generated by Django 4.1.6 on 2023-02-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, help_text='Укажите биографию автора', max_length=10000, verbose_name='Биография автора'),
        ),
    ]
