# Generated by Django 4.1.6 on 2023-02-20 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_alter_author_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read',
            field=models.ManyToManyField(blank=True, default=None, related_name='read', to=settings.AUTH_USER_MODEL),
        ),
    ]
